DROP TABLE IF EXISTS foods CASCADE;
CREATE TABLE foods (
  id SERIAL PRIMARY KEY NOT NULL,
  review_count INT NOT NULL,
  rating SMALLINT NOT NULL DEFAULT 0,
  phone_number BIGINT NOT NULL,
  website_url VARCHAR(255) NOT NULL DEFAULT '',
  address VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  user_id INT REFERENCES users(id) ON DELETE CASCADE
);

